### ISSUE TITLE
green titles

### ISSUE THREAD

**Issue by nicokant** [FirefoxMilano/FirefoxOS-Afternoon#5]
don't match the page style (let's talk about this ;) )

**Comment by aronnebrivio** [comment]
How about this one?
![schermata del 2015-04-25 15 59 23](https://cloud.githubusercontent.com/assets/6624657/7333161/100aa17c-eb64-11e4-984f-fa7b627c9327.png) (#F0733D)

Or this?
![schermata del 2015-04-25 16 00 04](https://cloud.githubusercontent.com/assets/6624657/7333164/26e73cd4-eb64-11e4-8ae1-c5f9e294cbb0.png) (#EB4E23)

(Picked from Firefox OS wallpaper used as header ;) )

**Comment by nicokant** [comment]
#EB4E23 seems perfect!
