### ISSUE TITLE
IRC client (non-web) are blocked by Eduroam

### ISSUE THREAD

**Issue by nicokant** [FirefoxMilano/FirefoxOS-Afternoon#6]
connections to irc by clients will be probably blocked by eduroam

**Comment by nicokant** [comment]
possible workaround:  add a iframe with a IRC web-client (https://kiwiirc.com/client)

cons: default server is freenode, we have to explain that irc server must be changed to irc.mozilla.org and with channel #developers-it

**Comment by aronnebrivio** [comment]
Unfortunately is not working, I tested yesterday...
BTW, with Firefox (seems not to be working on Chrome), by clicking on "Mozilla IRC" link on this page, which redirects to `irc://irc.mozilla.org` will open up a window like this one:
![schermata del 2015-04-25 15 53 25](https://cloud.githubusercontent.com/assets/6624657/7333143/40c0358a-eb63-11e4-8757-4ce582754203.png)
which opens up a new browser tab ready to connect to Mozilla IRC channel ;)
